"""initial schema

Revision ID: 24186308a2c1
Revises: 
Create Date: 2025-10-28 09:42:28.216785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24186308a2c1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'invoices', 'expense_accounts', ['expense_account_id'], ['id'])
    op.create_foreign_key(None, 'invoices', 'customers', ['customer_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'invoices', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'invoices', 'suppliers', ['supplier_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'invoices', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'invoices', 'invoices', ['duplicate_of'], ['id'])
    op.drop_constraint('suppliers_customer_id_ocr_supplier_identification_key', 'suppliers', type_='unique')
    op.create_unique_constraint('suppliers_customer_id_ocr_key', 'suppliers', ['customer_id', 'ocr_supplier_identification'])
    op.create_foreign_key(None, 'suppliers', 'customers', ['customer_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'suppliers', 'expense_accounts', ['default_expense_account_id'], ['id'])
    op.create_foreign_key(None, 'suppliers', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'users', 'customers', ['customer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'suppliers', type_='foreignkey')
    op.drop_constraint(None, 'suppliers', type_='foreignkey')
    op.drop_constraint(None, 'suppliers', type_='foreignkey')
    op.drop_constraint('suppliers_customer_id_ocr_key', 'suppliers', type_='unique')
    op.create_unique_constraint('suppliers_customer_id_ocr_supplier_identification_key', 'suppliers', ['customer_id', 'ocr_supplier_identification'])
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    # ### end Alembic commands ###
